name: Release Charts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Package controller chart
        run: |
          mkdir -p .cr-release-packages
          helm package charts/polyfea-controller -d .cr-release-packages
          
      - name: Update dependencies for samples chart
        run: |
          # Use the locally packaged controller chart as a file-based dependency
          mkdir -p charts/polyfea-md-shell-samples/charts
          cp .cr-release-packages/polyfea-controller-*.tgz charts/polyfea-md-shell-samples/charts/
          
      - name: Package samples chart
        run: |
          helm package charts/polyfea-md-shell-samples -d .cr-release-packages

      - name: Upload and index charts
        uses: helm/chart-releaser-action@main
        with:
          skip_existing: true
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
